name: Run Unit Tests

on:
  push:
    branches:
      - v2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: create env
        run: mkdir env

      - uses: actions/checkout@v3
      - name: get env
        uses: actions/checkout@v3
        with:
          repository: msng-devs/JGW-Secret
          ref: gatewayStorm
          path: "./env"
          token: ${{ secrets.TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --runInBand